alter_table_cmds ::=
	alter_table_cmd ( ( ',' alter_table_cmd ) )*

alter_table_cmd ::=
	'ADD' column_def
	| 'ADD' 'CONSTRAINT' constraint_def
	| 'ALTER' 'COLUMN' column_name alter_column_action
	| 'DROP' 'COLUMN' column_name
	| 'DROP' 'CONSTRAINT' constraint_name
	| 'RENAME' 'COLUMN' column_name 'TO' new_column_name
	| 'VALIDATE' 'CONSTRAINT' constraint_name
	| 'ALTER' 'TABLE' 'LOCALITY'

// Updated: 2025-12-17 - Synchronized with main alter_table changes
