create_policy_stmt ::=
	'CREATE' 'POLICY' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'ALL' 'TO' role_spec_list 'USING' '(' a_expr ')' 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'ALL' 'TO' role_spec_list 'WITH' 'CHECK' '(' a_expr ')' 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'ALL' 'TO' role_spec_list 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'ALL' 'TO' role_spec_list 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'ALL' 'TO' role_spec_list 
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'ALL'  'USING' '(' a_expr ')' 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'ALL'  'WITH' 'CHECK' '(' a_expr ')' 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'ALL'  'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'ALL'  'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'ALL'  
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'SELECT' 'TO' role_spec_list 'USING' '(' a_expr ')' 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'SELECT' 'TO' role_spec_list 'WITH' 'CHECK' '(' a_expr ')' 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'SELECT' 'TO' role_spec_list 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'SELECT' 'TO' role_spec_list 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'SELECT' 'TO' role_spec_list 
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'SELECT'  'USING' '(' a_expr ')' 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'SELECT'  'WITH' 'CHECK' '(' a_expr ')' 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'SELECT'  'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'SELECT'  'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'SELECT'  
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'INSERT' 'TO' role_spec_list 'USING' '(' a_expr ')' 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'INSERT' 'TO' role_spec_list 'WITH' 'CHECK' '(' a_expr ')' 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'INSERT' 'TO' role_spec_list 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'INSERT' 'TO' role_spec_list 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'INSERT' 'TO' role_spec_list 
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'INSERT'  'USING' '(' a_expr ')' 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'INSERT'  'WITH' 'CHECK' '(' a_expr ')' 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'INSERT'  'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'INSERT'  'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'INSERT'  
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'UPDATE' 'TO' role_spec_list 'USING' '(' a_expr ')' 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'UPDATE' 'TO' role_spec_list 'WITH' 'CHECK' '(' a_expr ')' 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'UPDATE' 'TO' role_spec_list 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'UPDATE' 'TO' role_spec_list 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'UPDATE' 'TO' role_spec_list 
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'UPDATE'  'USING' '(' a_expr ')' 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'UPDATE'  'WITH' 'CHECK' '(' a_expr ')' 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'UPDATE'  'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'UPDATE'  'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'UPDATE'  
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'DELETE' 'TO' role_spec_list 'USING' '(' a_expr ')' 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'DELETE' 'TO' role_spec_list 'WITH' 'CHECK' '(' a_expr ')' 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'DELETE' 'TO' role_spec_list 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'DELETE' 'TO' role_spec_list 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'DELETE' 'TO' role_spec_list 
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'DELETE'  'USING' '(' a_expr ')' 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'DELETE'  'WITH' 'CHECK' '(' a_expr ')' 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'DELETE'  'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'DELETE'  'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'DELETE'  
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'PERMISSIVE'  'TO' role_spec_list 'USING' '(' a_expr ')' 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'PERMISSIVE'  'TO' role_spec_list 'WITH' 'CHECK' '(' a_expr ')' 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'PERMISSIVE'  'TO' role_spec_list 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'PERMISSIVE'  'TO' role_spec_list 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'PERMISSIVE'  'TO' role_spec_list 
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'PERMISSIVE'   'USING' '(' a_expr ')' 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'PERMISSIVE'   'WITH' 'CHECK' '(' a_expr ')' 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'PERMISSIVE'   'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'PERMISSIVE'   'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'PERMISSIVE'   
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'ALL' 'TO' role_spec_list 'USING' '(' a_expr ')' 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'ALL' 'TO' role_spec_list 'WITH' 'CHECK' '(' a_expr ')' 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'ALL' 'TO' role_spec_list 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'ALL' 'TO' role_spec_list 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'ALL' 'TO' role_spec_list 
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'ALL'  'USING' '(' a_expr ')' 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'ALL'  'WITH' 'CHECK' '(' a_expr ')' 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'ALL'  'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'ALL'  'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'ALL'  
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'SELECT' 'TO' role_spec_list 'USING' '(' a_expr ')' 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'SELECT' 'TO' role_spec_list 'WITH' 'CHECK' '(' a_expr ')' 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'SELECT' 'TO' role_spec_list 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'SELECT' 'TO' role_spec_list 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'SELECT' 'TO' role_spec_list 
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'SELECT'  'USING' '(' a_expr ')' 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'SELECT'  'WITH' 'CHECK' '(' a_expr ')' 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'SELECT'  'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'SELECT'  'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'SELECT'  
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'INSERT' 'TO' role_spec_list 'USING' '(' a_expr ')' 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'INSERT' 'TO' role_spec_list 'WITH' 'CHECK' '(' a_expr ')' 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'INSERT' 'TO' role_spec_list 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'INSERT' 'TO' role_spec_list 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'INSERT' 'TO' role_spec_list 
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'INSERT'  'USING' '(' a_expr ')' 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'INSERT'  'WITH' 'CHECK' '(' a_expr ')' 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'INSERT'  'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'INSERT'  'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'INSERT'  
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'UPDATE' 'TO' role_spec_list 'USING' '(' a_expr ')' 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'UPDATE' 'TO' role_spec_list 'WITH' 'CHECK' '(' a_expr ')' 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'UPDATE' 'TO' role_spec_list 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'UPDATE' 'TO' role_spec_list 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'UPDATE' 'TO' role_spec_list 
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'UPDATE'  'USING' '(' a_expr ')' 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'UPDATE'  'WITH' 'CHECK' '(' a_expr ')' 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'UPDATE'  'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'UPDATE'  'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'UPDATE'  
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'DELETE' 'TO' role_spec_list 'USING' '(' a_expr ')' 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'DELETE' 'TO' role_spec_list 'WITH' 'CHECK' '(' a_expr ')' 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'DELETE' 'TO' role_spec_list 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'DELETE' 'TO' role_spec_list 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'DELETE' 'TO' role_spec_list 
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'DELETE'  'USING' '(' a_expr ')' 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'DELETE'  'WITH' 'CHECK' '(' a_expr ')' 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'DELETE'  'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'DELETE'  'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'DELETE'  
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'RESTRICTIVE'  'TO' role_spec_list 'USING' '(' a_expr ')' 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'RESTRICTIVE'  'TO' role_spec_list 'WITH' 'CHECK' '(' a_expr ')' 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'RESTRICTIVE'  'TO' role_spec_list 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'RESTRICTIVE'  'TO' role_spec_list 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'RESTRICTIVE'  'TO' role_spec_list 
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'RESTRICTIVE'   'USING' '(' a_expr ')' 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'RESTRICTIVE'   'WITH' 'CHECK' '(' a_expr ')' 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'RESTRICTIVE'   'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'RESTRICTIVE'   'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name 'AS' 'RESTRICTIVE'   
	| 'CREATE' 'POLICY' name 'ON' table_name  'FOR' 'ALL' 'TO' role_spec_list 'USING' '(' a_expr ')' 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name  'FOR' 'ALL' 'TO' role_spec_list 'WITH' 'CHECK' '(' a_expr ')' 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name  'FOR' 'ALL' 'TO' role_spec_list 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name  'FOR' 'ALL' 'TO' role_spec_list 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name  'FOR' 'ALL' 'TO' role_spec_list 
	| 'CREATE' 'POLICY' name 'ON' table_name  'FOR' 'ALL'  'USING' '(' a_expr ')' 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name  'FOR' 'ALL'  'WITH' 'CHECK' '(' a_expr ')' 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name  'FOR' 'ALL'  'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name  'FOR' 'ALL'  'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name  'FOR' 'ALL'  
	| 'CREATE' 'POLICY' name 'ON' table_name  'FOR' 'SELECT' 'TO' role_spec_list 'USING' '(' a_expr ')' 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name  'FOR' 'SELECT' 'TO' role_spec_list 'WITH' 'CHECK' '(' a_expr ')' 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name  'FOR' 'SELECT' 'TO' role_spec_list 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name  'FOR' 'SELECT' 'TO' role_spec_list 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name  'FOR' 'SELECT' 'TO' role_spec_list 
	| 'CREATE' 'POLICY' name 'ON' table_name  'FOR' 'SELECT'  'USING' '(' a_expr ')' 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name  'FOR' 'SELECT'  'WITH' 'CHECK' '(' a_expr ')' 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name  'FOR' 'SELECT'  'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name  'FOR' 'SELECT'  'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name  'FOR' 'SELECT'  
	| 'CREATE' 'POLICY' name 'ON' table_name  'FOR' 'INSERT' 'TO' role_spec_list 'USING' '(' a_expr ')' 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name  'FOR' 'INSERT' 'TO' role_spec_list 'WITH' 'CHECK' '(' a_expr ')' 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name  'FOR' 'INSERT' 'TO' role_spec_list 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name  'FOR' 'INSERT' 'TO' role_spec_list 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name  'FOR' 'INSERT' 'TO' role_spec_list 
	| 'CREATE' 'POLICY' name 'ON' table_name  'FOR' 'INSERT'  'USING' '(' a_expr ')' 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name  'FOR' 'INSERT'  'WITH' 'CHECK' '(' a_expr ')' 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name  'FOR' 'INSERT'  'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name  'FOR' 'INSERT'  'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name  'FOR' 'INSERT'  
	| 'CREATE' 'POLICY' name 'ON' table_name  'FOR' 'UPDATE' 'TO' role_spec_list 'USING' '(' a_expr ')' 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name  'FOR' 'UPDATE' 'TO' role_spec_list 'WITH' 'CHECK' '(' a_expr ')' 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name  'FOR' 'UPDATE' 'TO' role_spec_list 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name  'FOR' 'UPDATE' 'TO' role_spec_list 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name  'FOR' 'UPDATE' 'TO' role_spec_list 
	| 'CREATE' 'POLICY' name 'ON' table_name  'FOR' 'UPDATE'  'USING' '(' a_expr ')' 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name  'FOR' 'UPDATE'  'WITH' 'CHECK' '(' a_expr ')' 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name  'FOR' 'UPDATE'  'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name  'FOR' 'UPDATE'  'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name  'FOR' 'UPDATE'  
	| 'CREATE' 'POLICY' name 'ON' table_name  'FOR' 'DELETE' 'TO' role_spec_list 'USING' '(' a_expr ')' 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name  'FOR' 'DELETE' 'TO' role_spec_list 'WITH' 'CHECK' '(' a_expr ')' 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name  'FOR' 'DELETE' 'TO' role_spec_list 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name  'FOR' 'DELETE' 'TO' role_spec_list 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name  'FOR' 'DELETE' 'TO' role_spec_list 
	| 'CREATE' 'POLICY' name 'ON' table_name  'FOR' 'DELETE'  'USING' '(' a_expr ')' 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name  'FOR' 'DELETE'  'WITH' 'CHECK' '(' a_expr ')' 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name  'FOR' 'DELETE'  'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name  'FOR' 'DELETE'  'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name  'FOR' 'DELETE'  
	| 'CREATE' 'POLICY' name 'ON' table_name   'TO' role_spec_list 'USING' '(' a_expr ')' 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name   'TO' role_spec_list 'WITH' 'CHECK' '(' a_expr ')' 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name   'TO' role_spec_list 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name   'TO' role_spec_list 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name   'TO' role_spec_list 
	| 'CREATE' 'POLICY' name 'ON' table_name    'USING' '(' a_expr ')' 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name    'WITH' 'CHECK' '(' a_expr ')' 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name    'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name    'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' name 'ON' table_name    
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'ALL' 'TO' role_spec_list 'USING' '(' a_expr ')' 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'ALL' 'TO' role_spec_list 'WITH' 'CHECK' '(' a_expr ')' 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'ALL' 'TO' role_spec_list 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'ALL' 'TO' role_spec_list 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'ALL' 'TO' role_spec_list 
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'ALL'  'USING' '(' a_expr ')' 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'ALL'  'WITH' 'CHECK' '(' a_expr ')' 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'ALL'  'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'ALL'  'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'ALL'  
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'SELECT' 'TO' role_spec_list 'USING' '(' a_expr ')' 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'SELECT' 'TO' role_spec_list 'WITH' 'CHECK' '(' a_expr ')' 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'SELECT' 'TO' role_spec_list 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'SELECT' 'TO' role_spec_list 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'SELECT' 'TO' role_spec_list 
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'SELECT'  'USING' '(' a_expr ')' 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'SELECT'  'WITH' 'CHECK' '(' a_expr ')' 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'SELECT'  'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'SELECT'  'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'SELECT'  
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'INSERT' 'TO' role_spec_list 'USING' '(' a_expr ')' 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'INSERT' 'TO' role_spec_list 'WITH' 'CHECK' '(' a_expr ')' 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'INSERT' 'TO' role_spec_list 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'INSERT' 'TO' role_spec_list 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'INSERT' 'TO' role_spec_list 
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'INSERT'  'USING' '(' a_expr ')' 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'INSERT'  'WITH' 'CHECK' '(' a_expr ')' 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'INSERT'  'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'INSERT'  'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'INSERT'  
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'UPDATE' 'TO' role_spec_list 'USING' '(' a_expr ')' 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'UPDATE' 'TO' role_spec_list 'WITH' 'CHECK' '(' a_expr ')' 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'UPDATE' 'TO' role_spec_list 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'UPDATE' 'TO' role_spec_list 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'UPDATE' 'TO' role_spec_list 
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'UPDATE'  'USING' '(' a_expr ')' 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'UPDATE'  'WITH' 'CHECK' '(' a_expr ')' 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'UPDATE'  'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'UPDATE'  'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'UPDATE'  
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'DELETE' 'TO' role_spec_list 'USING' '(' a_expr ')' 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'DELETE' 'TO' role_spec_list 'WITH' 'CHECK' '(' a_expr ')' 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'DELETE' 'TO' role_spec_list 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'DELETE' 'TO' role_spec_list 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'DELETE' 'TO' role_spec_list 
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'DELETE'  'USING' '(' a_expr ')' 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'DELETE'  'WITH' 'CHECK' '(' a_expr ')' 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'DELETE'  'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'DELETE'  'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'PERMISSIVE' 'FOR' 'DELETE'  
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'PERMISSIVE'  'TO' role_spec_list 'USING' '(' a_expr ')' 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'PERMISSIVE'  'TO' role_spec_list 'WITH' 'CHECK' '(' a_expr ')' 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'PERMISSIVE'  'TO' role_spec_list 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'PERMISSIVE'  'TO' role_spec_list 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'PERMISSIVE'  'TO' role_spec_list 
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'PERMISSIVE'   'USING' '(' a_expr ')' 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'PERMISSIVE'   'WITH' 'CHECK' '(' a_expr ')' 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'PERMISSIVE'   'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'PERMISSIVE'   'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'PERMISSIVE'   
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'ALL' 'TO' role_spec_list 'USING' '(' a_expr ')' 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'ALL' 'TO' role_spec_list 'WITH' 'CHECK' '(' a_expr ')' 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'ALL' 'TO' role_spec_list 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'ALL' 'TO' role_spec_list 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'ALL' 'TO' role_spec_list 
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'ALL'  'USING' '(' a_expr ')' 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'ALL'  'WITH' 'CHECK' '(' a_expr ')' 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'ALL'  'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'ALL'  'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'ALL'  
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'SELECT' 'TO' role_spec_list 'USING' '(' a_expr ')' 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'SELECT' 'TO' role_spec_list 'WITH' 'CHECK' '(' a_expr ')' 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'SELECT' 'TO' role_spec_list 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'SELECT' 'TO' role_spec_list 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'SELECT' 'TO' role_spec_list 
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'SELECT'  'USING' '(' a_expr ')' 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'SELECT'  'WITH' 'CHECK' '(' a_expr ')' 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'SELECT'  'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'SELECT'  'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'SELECT'  
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'INSERT' 'TO' role_spec_list 'USING' '(' a_expr ')' 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'INSERT' 'TO' role_spec_list 'WITH' 'CHECK' '(' a_expr ')' 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'INSERT' 'TO' role_spec_list 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'INSERT' 'TO' role_spec_list 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'INSERT' 'TO' role_spec_list 
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'INSERT'  'USING' '(' a_expr ')' 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'INSERT'  'WITH' 'CHECK' '(' a_expr ')' 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'INSERT'  'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'INSERT'  'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'INSERT'  
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'UPDATE' 'TO' role_spec_list 'USING' '(' a_expr ')' 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'UPDATE' 'TO' role_spec_list 'WITH' 'CHECK' '(' a_expr ')' 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'UPDATE' 'TO' role_spec_list 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'UPDATE' 'TO' role_spec_list 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'UPDATE' 'TO' role_spec_list 
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'UPDATE'  'USING' '(' a_expr ')' 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'UPDATE'  'WITH' 'CHECK' '(' a_expr ')' 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'UPDATE'  'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'UPDATE'  'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'UPDATE'  
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'DELETE' 'TO' role_spec_list 'USING' '(' a_expr ')' 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'DELETE' 'TO' role_spec_list 'WITH' 'CHECK' '(' a_expr ')' 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'DELETE' 'TO' role_spec_list 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'DELETE' 'TO' role_spec_list 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'DELETE' 'TO' role_spec_list 
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'DELETE'  'USING' '(' a_expr ')' 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'DELETE'  'WITH' 'CHECK' '(' a_expr ')' 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'DELETE'  'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'DELETE'  'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'RESTRICTIVE' 'FOR' 'DELETE'  
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'RESTRICTIVE'  'TO' role_spec_list 'USING' '(' a_expr ')' 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'RESTRICTIVE'  'TO' role_spec_list 'WITH' 'CHECK' '(' a_expr ')' 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'RESTRICTIVE'  'TO' role_spec_list 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'RESTRICTIVE'  'TO' role_spec_list 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'RESTRICTIVE'  'TO' role_spec_list 
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'RESTRICTIVE'   'USING' '(' a_expr ')' 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'RESTRICTIVE'   'WITH' 'CHECK' '(' a_expr ')' 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'RESTRICTIVE'   'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'RESTRICTIVE'   'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name 'AS' 'RESTRICTIVE'   
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name  'FOR' 'ALL' 'TO' role_spec_list 'USING' '(' a_expr ')' 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name  'FOR' 'ALL' 'TO' role_spec_list 'WITH' 'CHECK' '(' a_expr ')' 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name  'FOR' 'ALL' 'TO' role_spec_list 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name  'FOR' 'ALL' 'TO' role_spec_list 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name  'FOR' 'ALL' 'TO' role_spec_list 
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name  'FOR' 'ALL'  'USING' '(' a_expr ')' 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name  'FOR' 'ALL'  'WITH' 'CHECK' '(' a_expr ')' 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name  'FOR' 'ALL'  'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name  'FOR' 'ALL'  'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name  'FOR' 'ALL'  
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name  'FOR' 'SELECT' 'TO' role_spec_list 'USING' '(' a_expr ')' 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name  'FOR' 'SELECT' 'TO' role_spec_list 'WITH' 'CHECK' '(' a_expr ')' 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name  'FOR' 'SELECT' 'TO' role_spec_list 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name  'FOR' 'SELECT' 'TO' role_spec_list 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name  'FOR' 'SELECT' 'TO' role_spec_list 
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name  'FOR' 'SELECT'  'USING' '(' a_expr ')' 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name  'FOR' 'SELECT'  'WITH' 'CHECK' '(' a_expr ')' 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name  'FOR' 'SELECT'  'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name  'FOR' 'SELECT'  'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name  'FOR' 'SELECT'  
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name  'FOR' 'INSERT' 'TO' role_spec_list 'USING' '(' a_expr ')' 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name  'FOR' 'INSERT' 'TO' role_spec_list 'WITH' 'CHECK' '(' a_expr ')' 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name  'FOR' 'INSERT' 'TO' role_spec_list 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name  'FOR' 'INSERT' 'TO' role_spec_list 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name  'FOR' 'INSERT' 'TO' role_spec_list 
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name  'FOR' 'INSERT'  'USING' '(' a_expr ')' 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name  'FOR' 'INSERT'  'WITH' 'CHECK' '(' a_expr ')' 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name  'FOR' 'INSERT'  'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name  'FOR' 'INSERT'  'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name  'FOR' 'INSERT'  
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name  'FOR' 'UPDATE' 'TO' role_spec_list 'USING' '(' a_expr ')' 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name  'FOR' 'UPDATE' 'TO' role_spec_list 'WITH' 'CHECK' '(' a_expr ')' 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name  'FOR' 'UPDATE' 'TO' role_spec_list 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name  'FOR' 'UPDATE' 'TO' role_spec_list 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name  'FOR' 'UPDATE' 'TO' role_spec_list 
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name  'FOR' 'UPDATE'  'USING' '(' a_expr ')' 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name  'FOR' 'UPDATE'  'WITH' 'CHECK' '(' a_expr ')' 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name  'FOR' 'UPDATE'  'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name  'FOR' 'UPDATE'  'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name  'FOR' 'UPDATE'  
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name  'FOR' 'DELETE' 'TO' role_spec_list 'USING' '(' a_expr ')' 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name  'FOR' 'DELETE' 'TO' role_spec_list 'WITH' 'CHECK' '(' a_expr ')' 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name  'FOR' 'DELETE' 'TO' role_spec_list 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name  'FOR' 'DELETE' 'TO' role_spec_list 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name  'FOR' 'DELETE' 'TO' role_spec_list 
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name  'FOR' 'DELETE'  'USING' '(' a_expr ')' 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name  'FOR' 'DELETE'  'WITH' 'CHECK' '(' a_expr ')' 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name  'FOR' 'DELETE'  'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name  'FOR' 'DELETE'  'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name  'FOR' 'DELETE'  
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name   'TO' role_spec_list 'USING' '(' a_expr ')' 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name   'TO' role_spec_list 'WITH' 'CHECK' '(' a_expr ')' 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name   'TO' role_spec_list 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name   'TO' role_spec_list 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name   'TO' role_spec_list 
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name    'USING' '(' a_expr ')' 'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name    'WITH' 'CHECK' '(' a_expr ')' 'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name    'WITH' 'CHECK' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name    'USING' '(' a_expr ')'
	| 'CREATE' 'POLICY' 'IF' 'NOT' 'EXISTS' name 'ON' table_name    
